server:
  port: 9000

spring:
  application:
    name: fancy-gateway
  cloud:
    gateway:
      routes:
        - id: blog
          uri: http://localhost:8001
          predicates:
            - Path=/fancy/blog/**